#!/bin/bash
PROFILE_FILENAME="$( basename $0).conf"
HOME_PROFILES_FILE="$HOME/.$PROFILE_FILENAME"
PROFILES_FILE="$HOME_PROFILES_FILE"

function usage() {
	echo "Usage: $( basename $0) command [player]"
	echo "commands supported: "
	echo -e "\tplay"
	echo -e "\tpause"
	echo -e "\tplaypause"
	echo -e "\tnext"
	echo -e "\tprev"
	echo -e "\tfwd"
	echo -e "\trew"
	exit 1
}

CMD="$1"
shift
test "x$CMD" == "x" && usage

function player_cmd_create_conf_file() {
	echo "$@"
}

source $( which multiprofiles) || echo "Dependency missing: multiprofiles (from gum-shell-utils)" && exit 1

echo "CMD=$CMD; args=$@"

